use_frameworks!

platform :ios, '9.0'

target 'ZXExtension_Example' do
  pod 'ZXExtension', :path => '../ZXExtension.podspec'

  target 'ZXExtension_Tests' do
    inherit! :search_paths

    
  end
end
